Modify gateway keystore according to the ingress TLS
gravitee-io/gravitee-kubernetes-operator pull request #281
Opened 2023-02-28 09:12 UTC by kamiiiel

https://gravitee.atlassian.net/browse/APIM-626

2023-03-03 07:45 UTC, brasseld requested changes

2023-03-03 07:45 UTC, brasseld commented on config/samples/ingress/ingress-with-tls.yml
> +    gravitee.io/keystore: gtw-keystore-credentials
Can we try to avoid that sort of thing for handling ingresses ?
In my mind, someone who's moving ingress to gravitee IC shouldn't  care specificities to ease the migration.
Happy to discuss that one @kamiiiel

2023-03-03 07:45 UTC, brasseld commented on config/samples/ingress/ingress-with-tls.yml
> +    gravitee.io/ingress: graviteeio
What's the purpose of that line ?

2023-03-03 07:45 UTC, brasseld commented on controllers/apim/ingress/internal/key_store.go
> +func (d *Delegate) UpdateGatewayKeyStore(ingress *v1.Ingress) error {
In the future, will need to make sure that the keystore is updated when one of the secret entry is itself updated (by cert-manager for example).

2023-03-03 07:45 UTC, brasseld commented on controllers/apim/ingress/internal/key_store.go
> +		name:     string(s.Data["name"]),
IMHO, these information should probably come from the operator configuration itself, not from a secret. wdyt ?

2023-03-03 07:48 UTC, kamiiiel commented on config/samples/ingress/ingress-with-tls.yml
> +    gravitee.io/keystore: gtw-keystore-credentials
Sure, but at the end we need to know the name and the password of the GW keystore

2023-03-03 07:50 UTC, kamiiiel commented on controllers/apim/ingress/internal/key_store.go
> +		name:     string(s.Data["name"]),
Then it needs restating the operator.

2023-03-03 07:50 UTC, brasseld commented on config/samples/ingress/ingress-with-tls.yml
> +    gravitee.io/keystore: gtw-keystore-credentials
Agree, why I'm proposing this https://github.com/gravitee-io/gravitee-kubernetes-operator/pull/281#discussion_r1124117935

2023-03-03 07:51 UTC, kamiiiel commented on config/samples/ingress/ingress-with-tls.yml
> +    gravitee.io/ingress: graviteeio
I guess this is something added by @a-cordier

2023-03-03 07:52 UTC, brasseld commented on controllers/apim/ingress/internal/key_store.go
> +		name:     string(s.Data["name"]),
You mean, when we change the credentials ?
In that case, why not using a secret by default (something like gravitee-ic-credentials) which can be override using operator's configuration. So by default, we'll stick to the default secret, or we can let the ingress owner to override the value. wdyt ?

2023-03-03 07:53 UTC, brasseld commented on config/samples/ingress/ingress-with-tls.yml
> +    gravitee.io/ingress: graviteeio
Ok, is this required ?

2023-03-03 07:58 UTC, brasseld commented on controllers/apim/ingress/internal/key_store.go
> +		name:     string(s.Data["name"]),
I don't get this one, can we have a 📞 for discussing it ?

2023-03-03 08:22 UTC, kamiiiel commented on config/samples/ingress/ingress-with-tls.yml
> +    gravitee.io/ingress: graviteeio
This seems to be only for the tests. We get all the ingresses with this label and we delete them after the tests. No other use case, it doesn't need to be added by the users.

2023-03-03 09:17 UTC, a-cordier commented on test/ingress_controller_delete_test.go
> +			}, timeout, interval).Should(BeTrue())
I find boolean assertion quite hard to understand when the CI fails. You just get a "expected false to be true" message. Maybe we should consider returning a meaning full error and `ShouldNot(HaveOccurred())` ? For the nil test I guess we could push it to the assertion.go file (AssertNotNil) to make it reusable

2023-03-03 09:17 UTC, a-cordier commented on test/ingress_controller_create_test.go
> +			}, timeout, interval).Should(BeTrue())
same comment as below about the boolean assertion

2023-03-03 09:17 UTC, a-cordier commented on controllers/apim/ingress/internal/key_store.go
> +	for _, rule := range ingress.Spec.Rules {
The linter is happy because of the comment, but sonar is not https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&pullRequest=281&id=gravitee-io_gravitee-kubernetes-operator&open=AYaiVHa9uCkWqpzJ7IFU

I'm wondering if instead of silenting two flags, we should not consider a refactoring, at least extracted some of the nested logic to dedicated methods

2023-03-07 15:03 UTC, kamiiiel commented on controllers/apim/ingress/internal/key_store.go
> +func (d *Delegate) UpdateGatewayKeyStore(ingress *v1.Ingress) error {
It should be fine now

2023-03-07 15:04 UTC, kamiiiel commented on controllers/apim/ingress/internal/key_store.go
> +		name:     string(s.Data["name"]),
Now it comes from a secret that the user can specify the name or it has a default name as well

2023-03-16 08:51 UTC, merged

2023-05-26 13:47 UTC, graviteeio commented
:tada: This PR is included in version 0.6.0 :tada:

The release is available on [GitHub release](https://github.com/gravitee-io/gravitee-kubernetes-operator/releases/tag/0.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: